language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker tag udagram-api-user gantonop/udagram-api-user:1.0
  - docker tag udagram-api-feed gantonop/udagram-api-feed:1.0
  - docker tag udagram-frondend gantonop/udagram-frontend:1.0
  - docker tag udagram-reverseproxy gantonop/udagram-reverseproxy:1.0

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gantonop/udagram-api-user
  - docker push gantonop/udagram-api-feed
  - docker push gantonop/udagram-frontend
  - docker push gantonop/udagram-reverseproxy
