language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker rmi -f $(docker images -f "dangling=true" -q)
  - docker-compose --env-file project/set_env.sh  -f project/docker-compose-build.yaml build --parallel 
  - docker tag udagram-api-user:latest gantonop/udagram-api-user:1.0
  - docker tag udagram-api-feed:latest gantonop/udagram-api-feed:1.0
  - docker tag udagram-frondend:latest gantonop/udagram-frontend:1.0
  - docker tag udagram-reverseproxy:latest gantonop/udagram-reverseproxy:1.0

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gantonop/udagram-api-user:1.0
  - docker push gantonop/udagram-api-feed:1.0
  - docker push gantonop/udagram-frontend:1.0
  - docker push gantonop/udagram-reverseproxy:1.0
