apiVersion: v1
kind: Service
metadata:
  labels:
    service: simple-express-rp
  name: simple-express-rp-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: simple-express-rp
