apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  ports:
    - port: 8100
      targetPort: 80 #This is the target container port
      protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer
