version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: gantonop/udagram-reverseproxy:3.0
  backend_user:
    build:
      context: ./udagram-api-user
    image: gantonop/udagram-api-user:3.0
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: gantonop/udagram-api-feed:3.0
  frontend:
    build:
      context: ./udagram-frontend
    image: gantonop/udagram-frontend:3.0
